# Generated by Django 2.1.2 on 2018-11-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.TextField(blank=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='조회수'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=100, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='impression',
            name='comment',
            field=models.TextField(blank=True, verbose_name='댓글'),
        ),
    ]
