# Generated by Django 2.1.2 on 2018-11-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20181102_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='impression',
            name='replyname',
            field=models.CharField(blank=True, max_length=100, verbose_name='작성자'),
        ),
    ]
