# Generated by Django 2.1.2 on 2018-11-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_impression_replyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='impression',
            name='replydate',
            field=models.DateTimeField(null=True, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=100, verbose_name='작성자'),
        ),
    ]
