# Generated by Django 2.1.2 on 2018-11-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20181102_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name='등록일1'),
        ),
        migrations.AddField(
            model_name='impression',
            name='replymodify_date',
            field=models.DateTimeField(auto_now=True, verbose_name='등록일2'),
        ),
    ]
