# Generated by Django 2.1.2 on 2018-11-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20181102_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='price',
            new_name='clicks',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date',
        ),
        migrations.RemoveField(
            model_name='impression',
            name='replydate',
        ),
        migrations.AlterField(
            model_name='book',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='impression',
            name='replymodify_date',
            field=models.DateTimeField(auto_now=True, verbose_name='등록일'),
        ),
    ]
