# Generated by Django 2.1.2 on 2018-11-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20181105_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='book',
            name='modify_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='impression',
            name='replymodify_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일'),
        ),
    ]
