# Generated by Django 2.1.2 on 2018-11-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('user_pwd', models.CharField(max_length=30)),
                ('user_nick', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=40)),
                ('c_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
