# Generated by Django 2.1.2 on 2018-11-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='myAdress',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
